name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_VERSION: '20'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci --include=dev
          npm install tailwindcss @astrojs/tailwind @tailwindcss/typography autoprefixer
          npm install
        
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          GITHUB_ACTIONS: 'true'
          CLOUDRON_DEPLOY: 'false'
          SITE_URL: 'https://rccgis-uchicago.github.io'
          BASE_PATH: ''  # Empty for GitHub Pages root domain
          PUBLIC_BASE: ''  # Empty for GitHub Pages root domain
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
