name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_VERSION: '20'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          retention-days: 1
          
      - name: Prepare Cloudron deployment
        run: |
          # Create deployment directory and copy files
          mkdir -p deployment
          cp -r dist/* deployment/
          
          # List files for debugging
          echo "Files in deployment directory:"
          ls -la deployment/
          
      - name: Upload Cloudron deployment package
        uses: actions/upload-artifact@v4
        with:
          name: cloudron-deployment
          path: deployment/
          retention-days: 1
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
  deploy-cloudron:
    name: Deploy to Cloudron Surfer
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install Bitwarden CLI
        run: |
          npm install -g @bitwarden/cli
          
      - name: Install Surfer CLI
        run: npm install -g cloudron-surfer
        
      - name: Download Cloudron artifacts
        uses: actions/download-artifact@v4
        with:
          name: cloudron-deployment
          path: .
          
      - name: Verify deployment files
        run: |
          echo "Current directory structure:"
          ls -la
          
          echo "\nDeployment directory contents:"
          ls -la deployment/ || echo "No deployment directory found"
          
      - name: Configure and Deploy to Cloudron
        env:
          SURFER_TOKEN: ${{ secrets.SURFER_API_TOKEN }}
          SURFER_SERVER: ${{ secrets.SURFER_SERVER }}
        run: |
          surfer config --server $SURFER_SERVER --token $SURFER_TOKEN
          # Deploy all files from the deployment directory
          if [ -d "deployment" ]; then
            echo "Deploying files from deployment directory..."
            surfer put deployment/* /
          else
            echo "Error: deployment directory not found!"
            ls -la
            exit 1
          fi
