name: Fetch and Convert Workshop Materials

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'GitHub repo URL (e.g. https://github.com/pnsinha/Network-Analysis-and-Visualization)'
        required: true
      workshop_slug:
        description: 'Workshop slug (optional, defaults to repo name)'
        required: false

jobs:
  fetch-and-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Set up Python for nbconvert
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Jupyter nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Set up R for rmarkdown
        uses: r-lib/actions/setup-r@v2

      - name: Install rmarkdown
        run: |
          Rscript -e "install.packages('rmarkdown', repos='https://cloud.r-project.org')"

      - name: Run fetch and convert script
        run: |
          chmod +x scripts/fetch_and_convert_workshop_materials.sh
          ./scripts/fetch_and_convert_workshop_materials.sh "${{ github.event.inputs.repo_url }}" "${{ github.event.inputs.workshop_slug }}"

      - name: Commit and push converted materials
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add public/notebooks/*
          git commit -m "Auto-update: fetched and converted workshop materials from ${{ github.event.inputs.repo_url }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
